name: Run Test
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  test-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: false
      - name: Go Cache
        uses: actions/cache@v4
        with:
          restore-keys: |
            go-test-{{ runner.os }}-{{ hashFiles('**/go.sum') }}
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
      - name: gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Run tests
        run:  gotestsum --junitfile report.xml || true
