name: Run Test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: false
      - name: Go Cache
        uses: actions/cache@v4
        with:
          key: go-test-{{ runner.os }}-{{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-test-{{ runner.os }}-{{ hashFiles('**/go.sum') }}
            go-test-
            go-
          path: |
           ~/go/pkg/mod
           ~/.cache/go-build
      - name: gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Run tests
        run:  gotestsum --junitfile report.xml || true
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'report.xml'